### ISSUE TITLE
App-Idea- FuncSol-integral solver and graph visualiser

### ISSUE THREAD

**Issue by ishwariiic** [Divide-By-0/ideas-for-projects-people-would-use#30]
his is a function solver app built using python and Tkinter,it can solve linear equations upto 3 variables, display their graphs, solve integrals and differential equations and perform operations on matrices.It is very common problem for students to find a proper platform for solving calculus problems and verifying their answers, even more difficult to visualise it, this app solves their problem.

**Comment by Divide-By-0** [comment]
Hey! Unfortunately I don't think this satisfies the constraints or is a highly novel software app, as Wolfram Alpha is probably good enough for me here.
